// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1BZQFZcjqDQSCgb4i4zexubj-U-k8qLI',
    appId: '1:960146935182:web:27e6a9843e1c3b8cdee8df',
    messagingSenderId: '960146935182',
    projectId: 'travelmate-ac228',
    authDomain: 'travelmate-ac228.firebaseapp.com',
    storageBucket: 'travelmate-ac228.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUD5QcGf9xKZ2gzS9DO0BHeMtfxhTQXdE',
    appId: '1:960146935182:android:fbf7d2d7a0e086d8dee8df',
    messagingSenderId: '960146935182',
    projectId: 'travelmate-ac228',
    storageBucket: 'travelmate-ac228.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG2a6Xt0nrKuNWG0bEaKkDtWfDNWBkA5E',
    appId: '1:960146935182:ios:84bb1402bc398b6fdee8df',
    messagingSenderId: '960146935182',
    projectId: 'travelmate-ac228',
    storageBucket: 'travelmate-ac228.firebasestorage.app',
    iosBundleId: 'com.example.travelMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG2a6Xt0nrKuNWG0bEaKkDtWfDNWBkA5E',
    appId: '1:960146935182:ios:84bb1402bc398b6fdee8df',
    messagingSenderId: '960146935182',
    projectId: 'travelmate-ac228',
    storageBucket: 'travelmate-ac228.firebasestorage.app',
    iosBundleId: 'com.example.travelMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1BZQFZcjqDQSCgb4i4zexubj-U-k8qLI',
    appId: '1:960146935182:web:84cee4e0c18e0534dee8df',
    messagingSenderId: '960146935182',
    projectId: 'travelmate-ac228',
    authDomain: 'travelmate-ac228.firebaseapp.com',
    storageBucket: 'travelmate-ac228.firebasestorage.app',
  );
}
